# Generated by Django 4.1.2 on 2022-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=60)),
                ('actor', models.CharField(max_length=300)),
                ('img_url', models.ImageField(upload_to='')),
                ('time', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=2000)),
                ('yt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
