# Generated by Django 4.1.2 on 2022-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=2000)),
                ('img_url', models.ImageField(upload_to='')),
                ('yt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
